/**
 * Seed Script for RSA Keys (OIDC/JWKS)
 *
 * Usage:
 *   npx ts-node prisma/seed-rsa-keys.ts
 *
 * This script:
 * 1. Generates initial RSA key pair for OIDC
 * 2. Stores keys in database for JWKS endpoint
 * 3. Creates backup of keys in ./keys directory
 * 4. Outputs key information for configuration
 */

import { PrismaClient, RSAKeyStatus } from '@prisma/client'
import crypto from 'crypto'
import { promises as fs } from 'fs'
import path from 'path'

const prisma = new PrismaClient()

/**
 * Generate RSA key pair
 */
function generateRSAKeyPair() {
  const { publicKey, privateKey } = crypto.generateKeyPairSync('rsa', {
    modulusLength: 2048,
    publicKeyEncoding: {
      type: 'spki',
      format: 'pem'
    },
    privateKeyEncoding: {
      type: 'pkcs8',
      format: 'pem'
    }
  })

  const kid = `beautysvc_${Date.now().toString(36)}_${crypto.randomBytes(8).toString('hex')}`

  return { publicKey, privateKey, kid }
}

/**
 * Save keys to backup directory
 */
async function saveKeysToFile(publicKey: string, privateKey: string, kid: string) {
  try {
    const keysDir = path.join(process.cwd(), 'keys')
    await fs.mkdir(keysDir, { recursive: true })

    // Save private key (PROTECTED)
    const privateKeyPath = path.join(keysDir, `rsa_private_${kid}.pem`)
    await fs.writeFile(privateKeyPath, privateKey, { mode: 0o600 })

    // Save public key
    const publicKeyPath = path.join(keysDir, `rsa_public_${kid}.pem`)
    await fs.writeFile(publicKeyPath, publicKey)

    // Save metadata
    const metadataPath = path.join(keysDir, `rsa_metadata_${kid}.json`)
    await fs.writeFile(
      metadataPath,
      JSON.stringify(
        {
          kid,
          algorithm: 'RS256',
          use: 'sig',
          createdAt: new Date().toISOString(),
          privateKeyPath,
          publicKeyPath
        },
        null,
        2
      )
    )

    console.log(`✅ Keys saved to ${keysDir}`)
    return { privateKeyPath, publicKeyPath, metadataPath }
  } catch (error) {
    console.error('❌ Failed to save keys to file:', error)
    throw error
  }
}

/**
 * Seed RSA keys
 */
async function seedRSAKeys() {
  console.log('\n🔑 Starting RSA Key Seed...\n')

  try {
    // Check if we already have active keys
    const existingKeys = await prisma.rSAKey.findMany({
      where: { status: RSAKeyStatus.ACTIVE }
    })

    if (existingKeys.length > 0) {
      console.log(`⚠️  Found ${existingKeys.length} existing active key(s)`)
      console.log('   Keys:', existingKeys.map(k => k.kid))
      console.log('\n   To rotate keys, mark existing ones as INACTIVE and generate new ones\n')

      // Still allow adding additional keys for rotation
      const continueSeeding = process.argv.includes('--force')
      if (!continueSeeding) {
        console.log('   Use --force flag to add more keys')
        return
      }
    }

    // Generate new key pair
    console.log('🔐 Generating RSA-2048 key pair...')
    const { publicKey, privateKey, kid } = generateRSAKeyPair()
    console.log(`✅ Generated key with kid: ${kid}\n`)

    // Save to filesystem for backup
    console.log('💾 Saving keys to filesystem backup...')
    const filePaths = await saveKeysToFile(publicKey, privateKey, kid)

    // Save to database
    console.log('📝 Saving to database...')
    const rSAKey = await prisma.rSAKey.create({
      data: {
        kid,
        algorithm: 'RS256',
        publicKey,
        privateKey,
        status: RSAKeyStatus.ACTIVE,
        use: 'sig',
        issuedBy: 'seed-script',
        metadata: {
          version: '1.0',
          environment: process.env.NODE_ENV || 'development',
          note: 'Initial key generated by seed script'
        }
      }
    })

    console.log(`✅ Saved to database with ID: ${rSAKey.id}\n`)

    // Output configuration info
    console.log('📋 Configuration Information:')
    console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━')
    console.log(`Key ID (kid):        ${kid}`)
    console.log(`Algorithm:           RS256`)
    console.log(`Status:              ${rSAKey.status}`)
    console.log(`Use:                 ${rSAKey.use}`)
    console.log(`Created At:          ${rSAKey.createdAt.toISOString()}`)
    console.log(`Database ID:         ${rSAKey.id}`)
    console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━')

    console.log('\n📂 File Locations:')
    console.log(`  Private Key:       ${filePaths.privateKeyPath}`)
    console.log(`  Public Key:        ${filePaths.publicKeyPath}`)
    console.log(`  Metadata:          ${filePaths.metadataPath}`)

    console.log('\n🔐 Environment Variables to Set:')
    console.log(`  RSA_KID=${kid}`)
    console.log(`  RSA_ALGORITHM=RS256`)

    console.log('\n✅ RSA Key Seed Complete!\n')

    // Security warning
    console.log('⚠️  SECURITY REMINDERS:')
    console.log('  1. Store private key securely (AWS KMS, Vault, etc.)')
    console.log('  2. Never commit private keys to git')
    console.log('  3. Add keys/ directory to .gitignore')
    console.log('  4. Rotate keys every 90 days')
    console.log('  5. Keep last 3 keys for verification during rotation\n')
  } catch (error) {
    console.error('❌ Error during seed:', error)
    throw error
  } finally {
    await prisma.$disconnect()
  }
}

// Run seed
seedRSAKeys().catch(error => {
  console.error('Fatal error:', error)
  process.exit(1)
})
