import express from 'express'
import Joi from 'joi'
import bcrypt from 'bcrypt'
import { prisma } from '@beauty-platform/database'
import {
  generatePasswordResetToken,
  verifyPasswordResetToken,
  isTokenValid,
} from '../utils/passwordResetToken'
import { getPasswordResetConfirmationTemplate } from '../services/emailTemplates'

const router = express.Router()

const NOTIFICATION_SERVICE_URL = process.env.NOTIFICATION_SERVICE_URL

/**
 * POST /api/auth/password-reset/request
 * Request a password reset token
 */
router.post('/request', async (req, res) => {
  const { email } = req.body

  // Validate email
  if (!email || typeof email !== 'string') {
    return res.status(400).json({
      success: false,
      error: 'Email is required',
    })
  }

  try {
    // Find user by email
    const user = await prisma.user.findUnique({
      where: { email: email.toLowerCase() },
      select: {
        id: true,
        email: true,
        firstName: true,
      },
    })

    if (!user) {
      // For security: don't reveal if email exists
      return res.status(200).json({
        success: true,
        message: 'If this email exists, a password reset link has been sent',
      })
    }

    // Generate reset token
    const { token, hash, expiresAt } = generatePasswordResetToken(24)

    // Store hash in database
    await prisma.user.update({
      where: { id: user.id },
      data: {
        passwordResetToken: hash,
        passwordResetExpiresAt: expiresAt,
      },
    })

    // Create reset link
    const resetLink = `${
      process.env.FRONTEND_BASE_URL || 'https://salon.beauty.designcorp.eu'
    }/auth/reset-password?token=${token}`

    // Send email
    try {
      await fetch(`${NOTIFICATION_SERVICE_URL}/api/notify/email`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          to: user.email,
          subject: 'Сброс пароля на Beauty Platform',
          html: `
            <p>Привет, ${user.firstName}!</p>
            <p>Для сброса пароля перейдите по ссылке:</p>
            <p><a href="${resetLink}">Сбросить пароль</a></p>
            <p>Ссылка действительна 24 часа.</p>
            <p>Если вы не запрашивали сброс, просто проигнорируйте это письмо.</p>
          `,
          text: `Для сброса пароля перейдите по ссылке: ${resetLink}`,
        }),
      })
    } catch (emailError) {
      console.error('[Auth][Password Reset] Email send failed:', emailError)
    }

    res.status(200).json({
      success: true,
      message: 'If this email exists, a password reset link has been sent',
    })
  } catch (error) {
    console.error('[Auth][Password Reset] Request failed:', error)
    res.status(500).json({
      success: false,
      error: 'Failed to process password reset request',
    })
  }
})

/**
 * POST /api/auth/password-reset/verify
 * Verify token and set new password
 */
router.post('/verify', async (req, res) => {
  const schema = Joi.object({
    token: Joi.string().required().min(64).max(64),
    password: Joi.string().required().min(8).max(128),
  })

  const { error, value } = schema.validate(req.body)
  if (error) {
    return res.status(400).json({
      success: false,
      error: error.details[0].message,
    })
  }

  const { token, password } = value

  try {
    // Find user with valid reset token
    const user = await prisma.user.findFirst({
      where: {
        passwordResetToken: { not: null },
        passwordResetExpiresAt: { gt: new Date() },
      },
      select: {
        id: true,
        email: true,
        firstName: true,
        passwordResetToken: true,
        passwordResetExpiresAt: true,
      },
    })

    if (!user || !user.passwordResetToken || !user.passwordResetExpiresAt) {
      return res.status(400).json({
        success: false,
        error: 'Invalid or expired reset token',
      })
    }

    // Verify token
    if (!verifyPasswordResetToken(token, user.passwordResetToken)) {
      return res.status(400).json({
        success: false,
        error: 'Invalid reset token',
      })
    }

    // Check expiration
    if (!isTokenValid(user.passwordResetExpiresAt)) {
      return res.status(400).json({
        success: false,
        error: 'Reset token has expired',
      })
    }

    // Hash new password
    const hashedPassword = await bcrypt.hash(password, 10)

    // Update user password
    await prisma.user.update({
      where: { id: user.id },
      data: {
        password: hashedPassword,
        passwordAutoGenerated: false,
        passwordResetToken: null,
        passwordResetExpiresAt: null,
      },
    })

    // Send confirmation email
    try {
      await fetch(`${NOTIFICATION_SERVICE_URL}/api/notify/email`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          to: user.email,
          subject: 'Пароль успешно изменен',
          html: getPasswordResetConfirmationTemplate(user.firstName),
          text: 'Ваш пароль успешно изменен. Теперь вы можете войти с новым паролем.',
        }),
      })
    } catch (emailError) {
      console.error('[Auth][Password Reset] Confirmation email failed:', emailError)
    }

    res.status(200).json({
      success: true,
      message: 'Password has been reset successfully',
    })
  } catch (error) {
    console.error('[Auth][Password Reset] Verify failed:', error)
    res.status(500).json({
      success: false,
      error: 'Failed to reset password',
    })
  }
})

/**
 * GET /api/auth/password-reset/validate
 * Check if a reset token is valid
 */
router.get('/validate', async (req, res) => {
  const { token } = req.query

  if (!token || typeof token !== 'string') {
    return res.status(400).json({
      success: false,
      valid: false,
      error: 'Token is required',
    })
  }

  try {
    // This endpoint doesn't need to find the actual user
    // We just validate that the token format is correct and would be hashable
    if (token.length !== 64) {
      return res.status(200).json({
        success: true,
        valid: false,
      })
    }

    res.status(200).json({
      success: true,
      valid: true,
    })
  } catch (error) {
    console.error('[Auth][Password Reset] Validate failed:', error)
    res.status(500).json({
      success: false,
      error: 'Failed to validate token',
    })
  }
})

export default router
