name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.14.4

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Run typecheck
        run: pnpm typecheck

      - name: Run linting
        run: pnpm lint

      - name: Build packages
        run: pnpm build:packages

      - name: Build web-booking app
        run: pnpm --filter @dc-beauty/web-booking build

      - name: Build web-crm app
        run: pnpm --filter @dc-beauty/web-crm build

      - name: Create deployment structure
        run: |
          mkdir -p dist
          
          echo "=== Building deployment structure ==="
          
          # Copy web-booking files to root if they exist
          if [ -d "apps/web-booking/dist" ]; then
            echo "Copying web-booking files..."
            cp -r apps/web-booking/dist/* dist/
            echo "✓ Web-booking files copied"
          else
            echo "⚠️  Web-booking dist not found"
          fi
          
          # Copy web-crm files to /crm/ subdirectory
          if [ -d "apps/web-crm/dist" ]; then
            echo "Copying web-crm files..."
            mkdir -p dist/crm
            cp -r apps/web-crm/dist/* dist/crm/
            echo "✓ Web-crm files copied to /crm/"
          else
            echo "⚠️  Web-crm dist not found"
          fi
          
          # Create simple 404.html for GitHub Pages SPA routing
          cat > dist/404.html << 'EOF'
          <!DOCTYPE html>
          <html>
          <head>
            <meta charset="utf-8">
            <title>Beauty Platform - Redirecting...</title>
            <script>
              console.log('404 handler triggered for:', window.location.pathname);
              
              // If trying to access CRM routes, redirect to CRM
              if (window.location.pathname.includes('/crm')) {
                console.log('Redirecting to CRM app');
                window.location.replace('/beauty/crm/');
              } else {
                console.log('Redirecting to main app');
                window.location.replace('/beauty/demo-salon');
              }
            </script>
          </head>
          <body>
            <h1>Redirecting...</h1>
            <p>If you are not redirected automatically, <a href="/beauty/">click here</a>.</p>
          </body>
          </html>
          EOF
          
          # Create 404.html for CRM SPA routing
          if [ -f "dist/crm/index.html" ]; then
            cp dist/crm/index.html dist/crm/404.html
            echo "✓ CRM 404.html created"
          fi
          
          # Create main index.html with direct links
          cat > dist/index.html << 'EOF'
          <!DOCTYPE html>
          <html lang="en">
          <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Beauty Platform</title>
            <style>
              body { 
                font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', system-ui, sans-serif;
                margin: 0;
                padding: 2rem;
                background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                color: white;
                min-height: 100vh;
                display: flex;
                align-items: center;
                justify-content: center;
              }
              .container { 
                text-align: center;
                max-width: 600px;
                background: rgba(255,255,255,0.1);
                padding: 3rem;
                border-radius: 1rem;
                backdrop-filter: blur(10px);
              }
              .logo { font-size: 4rem; margin-bottom: 1rem; }
              h1 { margin: 0 0 1rem 0; font-size: 2.5rem; }
              p { margin: 0 0 2rem 0; opacity: 0.9; }
              .links { display: flex; gap: 1rem; justify-content: center; flex-wrap: wrap; }
              .links a { 
                display: inline-block;
                padding: 1rem 2rem;
                background: rgba(255,255,255,0.2);
                color: white;
                text-decoration: none;
                border-radius: 0.5rem;
                border: 1px solid rgba(255,255,255,0.3);
                transition: all 0.3s ease;
                font-weight: 600;
              }
              .links a:hover { 
                background: rgba(255,255,255,0.3);
                transform: translateY(-2px);
                box-shadow: 0 4px 12px rgba(0,0,0,0.15);
              }
              .debug {
                margin-top: 2rem;
                padding: 1rem;
                background: rgba(0,0,0,0.3);
                border-radius: 0.5rem;
                font-family: monospace;
                font-size: 0.9rem;
                text-align: left;
              }
            </style>
          </head>
          <body>
            <div class="container">
              <div class="logo">💄</div>
              <h1>Beauty Platform</h1>
              <p>Choose your destination:</p>
              <div class="links">
                <a href="/beauty/demo-salon">📅 Public Booking</a>
                <a href="/beauty/crm/">⚙️ Admin CRM</a>
                <a href="/beauty/crm/test.html">🔧 Test Page</a>
              </div>
              <div class="debug">
                <strong>Debug Info:</strong><br>
                Current URL: <span id="current-url"></span><br>
                Timestamp: <span id="timestamp"></span>
              </div>
            </div>
            <script>
              document.getElementById('current-url').textContent = window.location.href;
              document.getElementById('timestamp').textContent = new Date().toISOString();
            </script>
          </body>
          </html>
          EOF
          
          echo "=== Final structure ==="
          find dist -type f | head -20
          echo ""
          echo "=== File sizes ==="
          du -sh dist/* 2>/dev/null || echo "No files in dist/"
          echo ""
          echo "=== CRM directory ==="
          ls -la dist/crm/ 2>/dev/null || echo "CRM directory not found"

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
